### ISSUE TITLE
4k 해상도에서 창고 레이아웃이 맞지 않는 현상

### ISSUE THREAD

**Issue by h1046rmahoro** [phiDelPark/PoeTradeSearch#10]
![123](https://user-images.githubusercontent.com/2732648/119165661-b20e2980-ba98-11eb-8a62-716828ebfd58.gif)
![quad](https://user-images.githubusercontent.com/2732648/119165665-b33f5680-ba98-11eb-98a1-c3a4268d84a9.gif)

사용중 4k 해상도 바탕화면 배율 150% 에서 창고 레이아웃이 맞지 않습니다. 

윈도우 높은 dpi 설정을 변경 해 봐도 되지 않는것 같습니다.

창고 레이아웃 숫자 버튼도 클릭하면 위치 표시가 됐던것 같은데 지금은 클릭이 통과 됩니다.

**Comment by phiDelPark** [comment]
아직 테스트중인 기능으로 현재 1920 해상도에서만 작업중이라 빠른 시일에 수정할게요.

**Comment by phiDelPark** [comment]
제가 4k가 없어서 테스트는 못했지만 3.14.1.7 에서도 안되면 다시 댓글 주세요.

**Comment by h1046rmahoro** [comment]
감사합니다. 해결 됐습니다!
