### ISSUE TITLE
업데이트 후 검색 불가 현상

### ISSUE THREAD

**Issue by run898** [phiDelPark/PoeTradeSearch#11]
아래처럼 업뎃 후 검색이 안되요~
(3.14.1.9에서는 되요)
![image](https://user-images.githubusercontent.com/59505937/119409340-214a7e80-bd22-11eb-9768-98962083bca2.png)

**Comment by phiDelPark** [comment]
템코드 적어 주세요. 복사해서 여기 적어주세요.

**Comment by ceyamoon** [comment]
3.14.1.9에서 3.14.2.9로 업데이트하니 안되고
3.14.2.2에서 3.14.2.9로 업데이트하니 됩니다
안되는 증상은 아무 아이템이나 다 안되더라구요.
업데이트 이후에 폴더내 파일을 비교해보니 아래 첨부파일과 같습니다.
3.14.1.9에서 업데이트하고나서   PoeTradeSearch아래에
FilterEN.txt FilterKO.txt ItemsEN.txt, ItemsKo.txt Parser.txt StaticEN.txt StaticKO.txt를 삭제하고 재실행하니
정상동작합니다.  

![이미지 2개 폴더 비교](https://user-images.githubusercontent.com/3114509/119487566-850d8f80-bd94-11eb-81b5-b087ade7cb51.png)

**Comment by phiDelPark** [comment]
설정 파일이 업데이트중 실패했나봅니다. 말씀대로 그럴땐 설정 폴더를 삭제하시면됩니다.
