### ISSUE TITLE
카드 검색시 필터로 인한 검색불가현상

### ISSUE THREAD

**Issue by run898** [phiDelPark/PoeTradeSearch#3]
![버그2_창추가](https://user-images.githubusercontent.com/59505937/71766168-49c0b580-2f40-11ea-8c1f-6b9548f43fd4.png)

예언 카드에는 카드이름 외 검색 필터가 없어야할것으로 보이는데요,
시험(the trial)카드를 해당 프로그램으로 검색시 아이템 필터가 걸려서 조회 결과가 뜨지 않게 됩니다.
(확인 후 정상화되시면 이슈 닫으시면 될것 같습니다)

**Comment by phiDelPark** [comment]
d4b9a45a11064d87f09683e1c431416bc63a128c
