### ISSUE TITLE
기능 하나만 제안드립니다~~

### ISSUE THREAD

**Issue by BongsooJeong** [phiDelPark/PoeTradeSearch#4]
만들어주신 프로그램 정말 잘 사용하고 있는데요..
딱 한가지 기능 더 요청드리고 싶은것이 거래시의 support인데요..

POE 거래시 어려운 점이.. 외국인이 영어로 구매 메세지보내서 받았을 때..
아이템 이름이 영어로 'PRAXIS'인데 한국어로 '관습'이 바로 번역이 안되면..
위치로만 아이템 찾는 것이 참 난감합니다;; (심지어는 quad 탭이거나 하면 ㄷㄷ)

1. 아이템에서 CTRL-C를 눌렀을때 한글/영어 이름을 동시에 보여준다.
-> 이거만 되도 최소한 맞는 아이템인지 체크가 빨라질거 같구요..

2. 횡/열 숫자를 입력하면 아이템 위치를 highlight 해준다.. 
-> 다른 유틸에서 이 방식을 쓰는 듯 하네요..

3. 아이템 이름 번역기 제공(?)
-> PRAXIS를 입력하면 한국어로 관습인 아이템이라고 보여주는 기능?
...

이런거 되면 좋을 듯 합니다..
감사합니다!!

**Comment by phiDelPark** [comment]
1. 버전 3.9.2.0 부턴 이름 클릭해보세요. 한글/영어 표시됩니다.
2. 이 프로그램의 목적과 조금 다른것 같습니다.

**Comment by BongsooJeong** [comment]
감사합니다~~
