### ISSUE TITLE
서류작업과 병행하면 프로그램이 먹통이 됩니다

### ISSUE THREAD

**Issue by sogid92** [phiDelPark/PoeTradeSearch#5]
POE와 해당 애드온이 켜져있고,
오피스 워드에서 컨트롤 C, V 사용 후
다시 게임으로 돌아오면 컨트롤 C버튼이 먹히지가 않네요
재밌는점은 노트패드나 한컴 한글에서는 같은 방법으로 해봐도 이상없이 작동한다는 겁니다..
혹시 테스트 가능하실까요? ㅠㅠ

**Comment by phiDelPark** [comment]
운영체제와 오피스의 정확한 버전과 비트를 알아야할것 같습니다. 
그리고 그 버전이 제가 없다면 구할때까지 테스트가 어려울 수 있습니다.
그리고 혹시 모르니 Wiki > Q-A 를 보고 단축키를 변경해보시기 바랍니다.

**Comment by sogid92** [comment]
> 운영체제와 오피스의 정확한 버전과 비트를 알아야할것 같습니다.
> 그리고 그 버전이 제가 없다면 구할때까지 테스트가 어려울 수 있습니다.
> 그리고 혹시 모르니 Wiki > Q-A 를 보고 단축키를 변경해보시기 바랍니다.

OS: 윈10 64bit
오피스 365
사용중입니다.
일단 알려주신 방법대로 단축키 바꿔서 사용해볼게요 감사합니다!
