### ISSUE TITLE
POE data에 대해서

### ISSUE THREAD

**Issue by hiphop5782** [phiDelPark/PoeTradeSearch#6]
소스코드 잘 보고 있습니다.

직접 언패킹 하신건지 아니면 API 이용하신건지 질문드려도 될까요?

**Comment by phiDelPark** [comment]
필터는 api 를 이용했고요
https://www.pathofexile.com/api/trade/data/stats
그외 데이터는 아래 라이브러리를 사용했습니다.
https://github.com/MuxaJIbI4/libggpk
