### ISSUE TITLE
필터에 문제가 좀 있어보입니다.

### ISSUE THREAD

**Issue by sogid92** [phiDelPark/PoeTradeSearch#7]
근데 프로그램 자체 오류라기 보다는 공홈 거래소 문제가 큰거같음..

![](https://i.imgur.com/qMKPc7i.png)
먼저 저 공격 명중시 생명력을 체크했을 때 결과가 뜨지 않습니다.

![](https://i.imgur.com/p0TeYlc.png)
그리고 공홈 거래소 보면 같은 필터가 두개나 있더라구요
그래서 위에거로 눌러보면 마찬가지로 검색결과가 안나옴

![](https://i.imgur.com/eBmvbxB.png)
아래걸로 눌렀을때 비로소 결과가 뜹니다.

혹시 이부분 차후에 반영 가능하실지요 ㅠㅠ

**Comment by phiDelPark** [comment]
말씀대로 영문과 달리 한글은 번역이 같아서 생긴 오류네요. 다음 버전에 반영합니다. 
d50b6f511e6a5d4c15ac31b6c7a65b6565708781
