### ISSUE TITLE
해당 아이템 유형으로 검색시 크래시

### ISSUE THREAD

**Issue by j0n9m1n1** [phiDelPark/PoeTradeSearch#8]
현재 버전: PoeTradeSearch_3.10.0.0_FW4.6
아이템: https://pastebin.com/JpmMrVJX

옵션 설정 이미지
![image](https://user-images.githubusercontent.com/28619938/77055450-3e940680-6a14-11ea-9eb5-461c68163d76.png)

해당 옵션으로 시세 재검색 누르면 프로그램 다운(에러 없음)
거래소에서 찾기 클릭시 에러 발생
![image](https://user-images.githubusercontent.com/28619938/77055611-84e96580-6a14-11ea-9def-cf3d9f33621f.png)

![image](https://user-images.githubusercontent.com/28619938/77055630-903c9100-6a14-11ea-9df5-e4a3ba9598ee.png)

**Comment by phiDelPark** [comment]
34abeaf51bb545b7d1894e0625f39824871a15a6
제보 감사합니다.
